# Generated by Django 3.2 on 2022-01-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_add_fields_to_FilmWork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_fw', to='movies.person', verbose_name='person'),
        ),
    ]
